# Kullman Alexandru 323CA

build:
	javac Walsh.java Statistics.java Prinel.java Crypto.java

run-p1:
	java Walsh

run-p2:
	java Statistics

run-p3:
	java Prinel

run-p4:
	java Crypto

clean:
	rm -rf *.class